name: Build Mobile App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Cache Buildozer directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Build APK with Buildozer Action
        uses: akshaybabloo/gaction-kivy-buildozer@v1.12.0
        with:
          python-version: '3.10'
          buildozer-cmd: |
            buildozer init
            sed -i 's/requirements = python3,kivy/requirements = python3,kivy,arabic_reshaper,python-bidi/g' buildozer.spec
            sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
            buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
