name: Build Mobile App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev python3-dev lld autoconf automake libtool pkg-config zip unzip openjdk-17-jdk

      - name: Install Buildozer & Cython
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.0.0" buildozer arabic_reshaper python-bidi

      - name: Build Android APK
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
            sed -i 's/requirements = python3,kivy/requirements = python3,kivy,arabic_reshaper,python-bidi/g' buildozer.spec
          fi
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
          
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          buildozer -v android debug

      - name: Find and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
